---
- name:
  hosts: all
  become: true
  vars:
    git_repository: "https://github.com/lunarock/Ansible_roles.git"
    git_branch: "master"

  tasks:
    - name: Utwórz folder z rolami ansible
      file:
        path: /etc/ansible/roles
        mode: '0755'
        state: directory

    - name: Pobierz role z gita
      git:
        repo: "{{ git_repository }}"
        version: "{{ git_branch }}"
        dest: "/etc/ansible/roles"
